# Generated by Django 4.0.4 on 2022-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, 'напитки')], verbose_name='категории')),
                ('label', models.CharField(max_length=50, verbose_name='Ресторан')),
                ('food', models.CharField(max_length=50, verbose_name='Блюдо')),
            ],
        ),
    ]
